server:
  port: 5125
spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6125
      password: aredissecret
      timeout: 10000
  mongodb:
    uri: mongodb://localhost:27125/andy-springboot4-template-local
  kafka:
    bootstrap-servers: localhost:9125

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true